type: object
description: Configuration API
properties:
  components:
    type: object
    properties:
      handler-hello:
        type: object
        properties:
          type:
            type: string
          handler:
            type: object
            properties:
              name:
                type: string
              path:
                type: string